"""
ChromaDB-backed Vector Memory for NPC agents.

Each NPC gets its own ChromaDB collection.  Memories are stored with:
  - text content
  - embedding (auto-generated by ChromaDB)
  - metadata: npc_id, timestamp, memory_type, importance

Retrieval uses cosine-similarity search so that contextually relevant
past memories surface naturally during NPC reasoning.
"""

from __future__ import annotations

import logging
import time
import uuid
from dataclasses import dataclass
from typing import List, Optional

import hashlib

import chromadb
import chromadb.utils.embedding_functions as embedding_functions
from chromadb.config import Settings

logger = logging.getLogger(__name__)


class _HashEmbeddingFunction(embedding_functions.EmbeddingFunction):
    """
    Deterministic, dependency-free embedding function for testing and
    offline environments.  Encodes text as a 64-dimensional float vector
    derived from a SHA-256 hash, so semantically similar strings may not
    be "close" — use only when a real model is unavailable.
    """

    def __init__(self) -> None:
        pass  # Do not call super().__init__() — the Protocol base warns when called directly.

    def name(self) -> str:  # type: ignore[override]
        return "hash_embedding"

    def get_config(self) -> dict:  # type: ignore[override]
        return {}

    def build_from_config(self, config: dict) -> "_HashEmbeddingFunction":  # type: ignore[override]
        return _HashEmbeddingFunction()

    def __call__(self, input: list[str]) -> list[list[float]]:  # type: ignore[override]
        results = []
        for text in input:
            digest = hashlib.sha256(text.encode()).digest()  # 32 bytes
            # Repeat to 64 floats, normalise to [-1, 1].
            vec = [(b / 127.5) - 1.0 for b in (list(digest) * 2)[:64]]
            results.append(vec)
        return results


@dataclass
class MemoryEntry:
    id: str
    npc_id: str
    text: str
    timestamp: float
    memory_type: str          # "dialogue" | "observation" | "task" | "emotion"
    importance: float         # 0.0 – 1.0
    distance: Optional[float] = None   # populated on retrieval


class VectorMemory:
    """
    Persistent vector memory store backed by ChromaDB.

    One :class:`VectorMemory` instance is shared across all NPCs; each NPC
    uses a separate ChromaDB *collection*.

    :param persist_directory: Directory for ChromaDB persistence.
    :param embedding_function: Optional ChromaDB EmbeddingFunction.  When
        *None* the default sentence-transformers model is used if available;
        otherwise falls back to a lightweight hash-based function suitable
        for offline / testing environments.
    """

    def __init__(
        self,
        persist_directory: str = "./chroma_db",
        embedding_function: Optional[embedding_functions.EmbeddingFunction] = None,
    ) -> None:
        self._client = chromadb.PersistentClient(
            path=persist_directory,
            settings=Settings(anonymized_telemetry=False),
        )
        # Resolve embedding function.
        if embedding_function is not None:
            self._ef = embedding_function
        else:
            try:
                self._ef = embedding_functions.DefaultEmbeddingFunction()
            except Exception:
                logger.warning(
                    "Default embedding function unavailable; using hash-based fallback."
                )
                self._ef = _HashEmbeddingFunction()
        self._collections: dict[str, chromadb.Collection] = {}
        logger.info("VectorMemory initialised (persist_dir=%s)", persist_directory)

    # ------------------------------------------------------------------
    # Collection helpers
    # ------------------------------------------------------------------

    def _get_or_create_collection(self, npc_id: str) -> chromadb.Collection:
        if npc_id not in self._collections:
            self._collections[npc_id] = self._client.get_or_create_collection(
                name=f"npc_{npc_id}",
                metadata={"hnsw:space": "cosine"},
                embedding_function=self._ef,
            )
        return self._collections[npc_id]

    # ------------------------------------------------------------------
    # Write
    # ------------------------------------------------------------------

    def add_memory(
        self,
        npc_id: str,
        text: str,
        memory_type: str = "dialogue",
        importance: float = 0.5,
    ) -> str:
        """Store a new memory and return its unique id."""
        collection = self._get_or_create_collection(npc_id)
        memory_id = str(uuid.uuid4())
        now = time.time()
        collection.add(
            ids=[memory_id],
            documents=[text],
            metadatas=[
                {
                    "npc_id": npc_id,
                    "timestamp": now,
                    "memory_type": memory_type,
                    "importance": importance,
                }
            ],
        )
        logger.debug("Memory stored for %s [%s]: %.60s…", npc_id, memory_type, text)
        return memory_id

    # ------------------------------------------------------------------
    # Read
    # ------------------------------------------------------------------

    def search_memories(
        self,
        npc_id: str,
        query: str,
        n_results: int = 5,
        memory_type: Optional[str] = None,
    ) -> List[MemoryEntry]:
        """
        Return the *n_results* most semantically relevant memories for *query*.
        """
        collection = self._get_or_create_collection(npc_id)
        if collection.count() == 0:
            return []

        where = {"npc_id": npc_id}
        if memory_type:
            where["memory_type"] = memory_type  # type: ignore[assignment]

        results = collection.query(
            query_texts=[query],
            n_results=min(n_results, collection.count()),
            where=where,
            include=["documents", "metadatas", "distances"],
        )

        entries: List[MemoryEntry] = []
        for doc, meta, dist in zip(
            results["documents"][0],
            results["metadatas"][0],
            results["distances"][0],
        ):
            entries.append(
                MemoryEntry(
                    id=results["ids"][0][len(entries)],
                    npc_id=meta["npc_id"],
                    text=doc,
                    timestamp=meta["timestamp"],
                    memory_type=meta["memory_type"],
                    importance=meta["importance"],
                    distance=dist,
                )
            )
        return entries

    def get_recent_memories(self, npc_id: str, limit: int = 10) -> List[MemoryEntry]:
        """Return the *limit* most recently stored memories (chronological order)."""
        collection = self._get_or_create_collection(npc_id)
        count = collection.count()
        if count == 0:
            return []

        results = collection.get(
            where={"npc_id": npc_id},
            include=["documents", "metadatas"],
            limit=min(limit, count),
        )

        entries = [
            MemoryEntry(
                id=mid,
                npc_id=meta["npc_id"],
                text=doc,
                timestamp=meta["timestamp"],
                memory_type=meta["memory_type"],
                importance=meta["importance"],
            )
            for mid, doc, meta in zip(
                results["ids"], results["documents"], results["metadatas"]
            )
        ]
        # Sort by timestamp descending.
        entries.sort(key=lambda e: e.timestamp, reverse=True)
        return entries

    def delete_memory(self, npc_id: str, memory_id: str) -> None:
        collection = self._get_or_create_collection(npc_id)
        collection.delete(ids=[memory_id])

    def clear_memories(self, npc_id: str) -> None:
        """Remove all memories for *npc_id*."""
        self._client.delete_collection(f"npc_{npc_id}")
        self._collections.pop(npc_id, None)
        logger.info("Cleared all memories for NPC %s", npc_id)
